service: rimac-appointment-cl

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  stage: production
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
    NODE_PORT: 3000
    AWS_SNS_TOPIC_ARN:
      Fn::ImportValue: rimac-appointment-topic-arn
    DB_URL: mysql://admin:password123@mydb-instance.abcdefg12345.us-east-1.rds.amazonaws.com:3306/appointment_cl

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - events:PutEvents
      Resource:
        - Fn::GetAtt: [SQSCl, Arn]
        - Fn::ImportValue: rimac-appointment-SQSFromEventBridgeArn
        - '*'
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: '*'

functions:
  appointment-cl:
    handler: dist/lambda.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSCl, Arn]

resources:
  Resources:
    SQSCl:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs_cl

    SQSClPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: SQSCl
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: Allow-SNS-SendMessage
              Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: SQS:SendMessage
              Resource:
                Fn::GetAtt: [SQSCl, Arn]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Fn::ImportValue: rimac-appointment-topic-arn

    SnsSubscriptionCl:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Fn::ImportValue: rimac-appointment-topic-arn
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [SQSCl, Arn]
        FilterPolicy:
          countryISO:
            - CL

    EventBridgeRule:
      Type: AWS::Events::Rule
      Properties:
        EventPattern:
          source:
            - 'appointment.processor'
          detail-type:
            - 'AppointmentCompleted'
        Targets:
          - Arn:
              Fn::ImportValue: rimac-appointment-SQSFromEventBridgeArn
            Id: 'TargetSQS'
